<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Message Box</name>
   <tag></tag>
   <elementGuidId>2071bfe2-5d27-4a47-ae3d-4f0536b44c0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='Message Box']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2239929d-9b22-4274-802f-e441eb8215e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Message Box</value>
      <webElementGuid>ecce6da4-4a36-40f8-86b7-7b075e73cd45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>resp-tab-item</value>
      <webElementGuid>5e08ef4f-092f-4f71-bf62-adb4fe04bc61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>tab_item-1</value>
      <webElementGuid>687018f7-f934-450a-85aa-0772e7ff3f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>1d4deea0-a4e2-41c3-a078-8301dcd03623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Message Box</value>
      <webElementGuid>1dc61426-60f4-48a4-b22a-f5198d162001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Message Box&quot;)</value>
      <webElementGuid>30a5903c-caaa-4c56-8e2b-16ea851138ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='Message Box']</value>
      <webElementGuid>93833f8f-61b2-4146-a5d0-2f495219b9db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-2663']/div[2]/div/ul/li[2]</value>
      <webElementGuid>ca4df1a2-55c2-452c-aeca-2ed1f8406df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form'])[1]/following::li[1]</value>
      <webElementGuid>80cc7de6-e67a-4a05-87bd-5d7c6bf45e08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AngularJS Protractor Practice Site'])[3]/following::li[2]</value>
      <webElementGuid>acd12802-ce4d-46e6-8cae-d3736c30eaa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation Box'])[1]/preceding::li[1]</value>
      <webElementGuid>a49f0ef4-24ba-4a97-a875-0c68d0ff2279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form'])[2]/preceding::li[2]</value>
      <webElementGuid>fb432da0-da5f-4504-ba19-6ef39474f989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Message Box']/parent::*</value>
      <webElementGuid>2aabc840-2e64-4cbf-98e0-d797284630a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[2]</value>
      <webElementGuid>e9c00e6b-df41-4b2f-b153-24b7b4713548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'Message Box' and (text() = 'Message Box' or . = 'Message Box')]</value>
      <webElementGuid>400b28f9-d949-47a1-859f-9e792013e1ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
